name: Plan an Action
description: Create a detailed plan of action (ONLY START AFTER DISCUSSION PLEASE 🙏).
labels: [triage]
body:
- type: textarea
  attributes:
    label: Current Situation
    description: Discuss how things currently are, why they should change, and any relevant prior discussion/context.
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Actions
    description: Describe how things ought to be, and why that will address the reasons for change mentioned above.
  validations:
    required: false
- type: textarea
  attributes:
    label: Implementation Details
    description: |
      A thorough explanation for how the proposed change will be implemented and, if relevant, old behaviors deprecated.
  validations:
    required: false
